/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aquino.webParser.swing.autofill;

import com.aquino.webParser.model.AutoFillModel;
import com.aquino.webParser.swing.Handlers;

import java.awt.*;
import java.io.IOException;
import java.net.URI;

/**
 *
 * @author alex
 */
public class BookRow extends javax.swing.JPanel {

    private AutoFillModel autoFillModel;

    /**
     * Creates new form BookRow
     */
    public BookRow() {
        initComponents();
    }

    public BookRow(AutoFillModel model) {
        this();
        this.autoFillModel = model;
        if(autoFillModel.getAuthor() != null){
            textEnglishFirst.setText(autoFillModel.getAuthor().getEnglishFirstName());
            textEnglishLast.setText(autoFillModel.getAuthor().getEnglishLastName());
            textNativeFirst.setText(autoFillModel.getAuthor().getNativeFirstName());
            textNativeLast.setText(autoFillModel.getAuthor().getNativeLastName());
        }
        if(autoFillModel.getPublisher() != null){
            textPublisherEnglish.setText(autoFillModel.getPublisher().getEnglishName());
            textPublisherNative.setText(autoFillModel.getPublisher().getNativeName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkBox = new javax.swing.JCheckBox();
        textNativeFirst = new javax.swing.JTextField();
        textNativeLast = new javax.swing.JTextField();
        textEnglishFirst = new javax.swing.JTextField();
        textEnglishLast = new javax.swing.JTextField();
        buttonAuthorLink = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new Dimension(5, 5), new Dimension(40, 20), new Dimension(32767, 0));
        textPublisherNative = new javax.swing.JTextField();
        textPublisherEnglish = new javax.swing.JTextField();
        buttonPublisherLink = new javax.swing.JButton();

        setMaximumSize(new Dimension(2000, 50));
        setMinimumSize(new Dimension(200, 21));

        checkBox.setMinimumSize(new Dimension(10, 10));
        add(checkBox);

        textNativeFirst.setFont(new Font("HCR Batang", 0, 18)); // NOI18N
        textNativeFirst.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textNativeFirst.setText("native firstマガジンハウス");
        textNativeFirst.setMaximumSize(new Dimension(500, 50));
        textNativeFirst.setMinimumSize(new Dimension(200, 50));
        textNativeFirst.setPreferredSize(new Dimension(120, 40));
        textNativeFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNativeFirstActionPerformed(evt);
            }
        });
        add(textNativeFirst);
        textNativeFirst.getAccessibleContext().setAccessibleName("textAuthorNewFirst");

        textNativeLast.setFont(new Font("HCR Batang", 0, 18)); // NOI18N
        textNativeLast.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textNativeLast.setText("native last(후지오카 요오코");
        textNativeLast.setMaximumSize(new Dimension(500, 50));
        textNativeLast.setMinimumSize(new Dimension(200, 50));
        textNativeLast.setPreferredSize(new Dimension(120, 40));
        textNativeLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNativeLastActionPerformed(evt);
            }
        });
        add(textNativeLast);

        textEnglishFirst.setFont(new Font("HCR Batang", 0, 18)); // NOI18N
        textEnglishFirst.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textEnglishFirst.setText("english first");
        textEnglishFirst.setMaximumSize(new Dimension(500, 50));
        textEnglishFirst.setMinimumSize(new Dimension(200, 50));
        textEnglishFirst.setPreferredSize(new Dimension(120, 40));
        add(textEnglishFirst);

        textEnglishLast.setFont(new Font("HCR Batang", 0, 18)); // NOI18N
        textEnglishLast.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textEnglishLast.setText("english last");
        textEnglishLast.setMaximumSize(new Dimension(500, 50));
        textEnglishLast.setMinimumSize(new Dimension(200, 50));
        textEnglishLast.setPreferredSize(new Dimension(120, 40));
        add(textEnglishLast);

        buttonAuthorLink.setText("Link");
        add(buttonAuthorLink);
        add(filler2);

        textPublisherNative.setFont(new Font("HCR Batang", 0, 18)); // NOI18N
        textPublisherNative.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textPublisherNative.setText("native");
        textPublisherNative.setMaximumSize(new Dimension(500, 50));
        textPublisherNative.setMinimumSize(new Dimension(200, 50));
        textPublisherNative.setPreferredSize(new Dimension(120, 40));
        add(textPublisherNative);

        textPublisherEnglish.setFont(new Font("HCR Batang", 0, 18)); // NOI18N
        textPublisherEnglish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textPublisherEnglish.setText("english");
        textPublisherEnglish.setMaximumSize(new Dimension(500, 50));
        textPublisherEnglish.setMinimumSize(new Dimension(200, 50));
        textPublisherEnglish.setPreferredSize(new Dimension(120, 40));
        add(textPublisherEnglish);

        buttonPublisherLink.setText("Link");
        add(buttonPublisherLink);
    }// </editor-fold>//GEN-END:initComponents

    private void textNativeFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNativeFirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNativeFirstActionPerformed

    private void textNativeLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNativeLastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNativeLastActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAuthorLink;
    private javax.swing.JButton buttonPublisherLink;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JTextField textEnglishFirst;
    private javax.swing.JTextField textEnglishLast;
    private javax.swing.JTextField textNativeFirst;
    private javax.swing.JTextField textNativeLast;
    private javax.swing.JTextField textPublisherEnglish;
    private javax.swing.JTextField textPublisherNative;
    // End of variables declaration//GEN-END:variables


    public AutoFillModel getAutoFillModel() {
        updateModel();
        return autoFillModel;
    }

    private void updateModel() {
        if(autoFillModel.getAuthor() != null){
            autoFillModel.getAuthor().setEnglishFirstName(textEnglishFirst.getText());
            autoFillModel.getAuthor().setEnglishLastName(textEnglishLast.getText());
            autoFillModel.getAuthor().setNativeFirstName(textNativeFirst.getText());
            autoFillModel.getAuthor().setNativeLastName(textNativeLast.getText());
        }
        if(autoFillModel.getPublisher() != null){
            autoFillModel.getPublisher().setEnglishName(textPublisherEnglish.getText());
            autoFillModel.getPublisher().setNativeName(textPublisherNative.getText());
        }
    }

    public void setAuthorLink(int id, String link) {
        buttonAuthorLink.setAction(Handlers.anonymousEventClass(String.valueOf(id), actionEvent -> OpenLink(link)));
    }

    private void OpenLink(String link) {
        try {
            Desktop.getDesktop().browse(URI.create(link));
        } catch (IOException e) {
            //TODO send event to parent form to display error.
            e.printStackTrace();
        }
    }
    
    public void toggleIsChecked(boolean enable){
        this.checkBox.setSelected(enable); 
    }

    public boolean isSelected() {
        return this.checkBox.isSelected();
    }
}
