/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aquino.webParser;

/**
 *
 * @author alex
 */
public class BookRow extends javax.swing.JPanel {

    /**
     * Creates new form BookRow
     */
    public BookRow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(2000, 50));
        setMinimumSize(new java.awt.Dimension(200, 21));
        setLayout(new java.awt.GridLayout());

        jCheckBox1.setMinimumSize(new java.awt.Dimension(10, 10));
        add(jCheckBox1);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("original author");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(50, 50));
        add(jLabel1);
        jLabel1.getAccessibleContext().setAccessibleName("labelOriginalAuthor");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("firstname");
        jTextField1.setMaximumSize(new java.awt.Dimension(500, 50));
        jTextField1.setMinimumSize(new java.awt.Dimension(200, 50));
        jTextField1.setPreferredSize(new java.awt.Dimension(100, 20));
        add(jTextField1);
        jTextField1.getAccessibleContext().setAccessibleName("textAuthorNewFirst");

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("lastname");
        jTextField3.setMaximumSize(new java.awt.Dimension(100, 50));
        jTextField3.setMinimumSize(new java.awt.Dimension(50, 50));
        add(jTextField3);
        jTextField3.getAccessibleContext().setAccessibleName("textAuthorNewLast");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("new number link");
        jLabel3.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel3.setMinimumSize(new java.awt.Dimension(50, 50));
        add(jLabel3);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("link");
        jLabel4.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel4.setMinimumSize(new java.awt.Dimension(50, 50));
        add(jLabel4);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("original publisher");
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel2.setMinimumSize(new java.awt.Dimension(50, 50));
        add(jLabel2);
        jLabel2.getAccessibleContext().setAccessibleName("labelPublisherOld");

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("new publisher");
        jTextField2.setMaximumSize(new java.awt.Dimension(100, 50));
        jTextField2.setMinimumSize(new java.awt.Dimension(50, 50));
        add(jTextField2);
        jTextField2.getAccessibleContext().setAccessibleName("textPublisherNew");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("new number link");
        jLabel5.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel5.setMinimumSize(new java.awt.Dimension(50, 50));
        add(jLabel5);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
