/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aquino.webParser;

/**
 *
 * @author alex
 */
public class BookRow extends javax.swing.JPanel {

    /**
     * Creates new form BookRow
     */
    public BookRow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        textNativeFirst = new javax.swing.JTextField();
        textNativeLast = new javax.swing.JTextField();
        textEnglishFirst = new javax.swing.JTextField();
        textEnglishLast = new javax.swing.JTextField();
        buttonAuthorLink = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 5), new java.awt.Dimension(40, 20), new java.awt.Dimension(32767, 0));
        textPublisherNative = new javax.swing.JTextField();
        textPublisherEnglish = new javax.swing.JTextField();
        buttonPublisherLink = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(2000, 50));
        setMinimumSize(new java.awt.Dimension(200, 21));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jCheckBox1.setMinimumSize(new java.awt.Dimension(10, 10));
        add(jCheckBox1);

        textNativeFirst.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textNativeFirst.setText("native first");
        textNativeFirst.setMaximumSize(new java.awt.Dimension(500, 50));
        textNativeFirst.setMinimumSize(new java.awt.Dimension(200, 50));
        textNativeFirst.setPreferredSize(new java.awt.Dimension(100, 20));
        add(textNativeFirst);
        textNativeFirst.getAccessibleContext().setAccessibleName("textAuthorNewFirst");

        textNativeLast.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textNativeLast.setText("native last");
        textNativeLast.setMaximumSize(new java.awt.Dimension(500, 50));
        textNativeLast.setMinimumSize(new java.awt.Dimension(200, 50));
        textNativeLast.setPreferredSize(new java.awt.Dimension(100, 20));
        add(textNativeLast);

        textEnglishFirst.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textEnglishFirst.setText("english first");
        textEnglishFirst.setMaximumSize(new java.awt.Dimension(500, 50));
        textEnglishFirst.setMinimumSize(new java.awt.Dimension(200, 50));
        textEnglishFirst.setPreferredSize(new java.awt.Dimension(100, 20));
        add(textEnglishFirst);

        textEnglishLast.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textEnglishLast.setText("english last");
        textEnglishLast.setMaximumSize(new java.awt.Dimension(500, 50));
        textEnglishLast.setMinimumSize(new java.awt.Dimension(200, 50));
        textEnglishLast.setPreferredSize(new java.awt.Dimension(100, 20));
        add(textEnglishLast);

        buttonAuthorLink.setText("Link");
        add(buttonAuthorLink);
        add(filler2);

        textPublisherNative.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textPublisherNative.setText("native");
        textPublisherNative.setMaximumSize(new java.awt.Dimension(500, 50));
        textPublisherNative.setMinimumSize(new java.awt.Dimension(200, 50));
        textPublisherNative.setPreferredSize(new java.awt.Dimension(100, 20));
        add(textPublisherNative);

        textPublisherEnglish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textPublisherEnglish.setText("english");
        textPublisherEnglish.setMaximumSize(new java.awt.Dimension(500, 50));
        textPublisherEnglish.setMinimumSize(new java.awt.Dimension(200, 50));
        textPublisherEnglish.setPreferredSize(new java.awt.Dimension(100, 20));
        add(textPublisherEnglish);

        buttonPublisherLink.setText("Link");
        add(buttonPublisherLink);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAuthorLink;
    private javax.swing.JButton buttonPublisherLink;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JTextField textEnglishFirst;
    private javax.swing.JTextField textEnglishLast;
    private javax.swing.JTextField textNativeFirst;
    private javax.swing.JTextField textNativeLast;
    private javax.swing.JTextField textPublisherEnglish;
    private javax.swing.JTextField textPublisherNative;
    // End of variables declaration//GEN-END:variables
}
